# Parámetros de la función

### Parámetros Posicionales: Crear una función llamada multiplicar que reciba dos números y devuelva su producto. Probar la función con diferentes pares de números.

In [2]:
def multiplicar(num1:int, num2:int) -> int:
    return num1 * num2

print(multiplicar(1, 5))

5

### Parámetros por Defecto: Crear una función llamada bienvenida que reciba un nombre y un mensaje de bienvenida. El mensaje debe tener un valor por defecto de "¡Bienvenido!". Si no se proporciona un mensaje, la función debe usar el valor por defecto. Probar la función proporcionando solo el nombre y con el mensaje.

In [7]:
def bienvenida(nombre: str, bienvenida= "¡Bienvenido!") -> str:
    return f'Hola {nombre}, {bienvenida}'

print(bienvenida('Moises'))
print(bienvenida('Moises', 'Relax&Enjoy'))

Hola Moises, ¡Bienvenido!
Hola Moises, Relax&Enjoy

### Parámetros Indefinidos (*args): Crear una función llamada calcular_promedio que acepte un número variable de notas (posicionales) y devuelva el promedio de esas notas. Probar la función con diferentes cantidades de notas.

In [13]:
def calcular_promedio(*args: float) -> str:
    # print(type(args))
    return f'El promedio de las notas es {sum(args)/len(args)}'

print(calcular_promedio(7,8,9))

El promedio de las notas es 8.0

### Parámetros de Palabras Clave Indefinidas (**kwargs): Crear una función llamada concatena_info que reciba un nombre y un número indefinido de palabras clave (por ejemplo, edad, ciudad, ocupación) y devuelva un string que combine todos los datos. Probar la función pasando varios pares de clave-valor.

In [21]:
def concatena_info(nombre: str, **kwargs) -> str:
    return f'El usuario se llama {nombre}, tiene {kwargs.get('edad', 'desconocido')} años, vive en {kwargs.get('ciudad', 'desconocido')} y trabaja como {kwargs.get('ocupación', 'desconocido')}.'

print(concatena_info('Bob', edad= 45, ciudad='TrenchTown', ocupación= "Reggae Singer"))
print(concatena_info('Diego', ciudad='Villa Fiorito', ocupación= "D10S"))

El usuario se llama Bob, tiene 45 años, vive en TrenchTown y trabaja como Reggae Singer.
El usuario se llama Diego, tiene desconocido años, vive en Villa Fiorito y trabaja como D10S.

### Cargar un csv en Google Colab y visualizar sus primeras filas usando Pandas.

In [11]:
import pandas as pd
import openpyxl

### Carga de .csv

In [12]:
df = pd.read_csv(r"ventas - ventas.csv", sep = ',')
df.head(2)
df.sample(3, random_state= 42)

          Fecha     Vendedor Sede Entrega    Producto      Importe
199  30/12/2020  Vendedor 10       Sede A  Producto W   $78,771.17
422  24/04/2021   Vendedor 7       Sede A  Producto V  $342,045.09
695  26/12/2020   Vendedor 3       Sede D  Producto S   $27,000.44

### Carga de .xlsx

In [9]:
df_xlsx = pd.read_excel(r'ventas.xlsx')
df_xlsx.sample(3, random_state=42)

         Fecha     Vendedor Sede Entrega    Producto     Importe
199 2020-12-30  Vendedor 10       Sede A  Producto W   $78771.17
422 2021-04-24   Vendedor 7       Sede A  Producto V  $342045.09
695 2020-12-26   Vendedor 3       Sede D  Producto S   $27000.44